name: Translation

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
on:
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #   - '**.en.json' # only take action when *.en.json files change   
  push:
    branches: [ main ]
    paths:
    - '**.en.json' # only take action when *.en.json files change   
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  translate:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Get list of files that have been changed in the push
      - id: files
        uses: masesgroup/retrieve-changed-files@v2

      # Process the changed files
      - name: Work with the list of modified files
        id: translate
        env:
          AZURE_TRANSLATOR_SUBSCRIPTION_KEY: ${{ secrets.AZURE_TRANSLATOR_SUBSCRIPTION_KEY }}
          AZURE_TRANSLATOR_ENDPOINT: ${{ secrets.AZURE_TRANSLATOR_ENDPOINT }}
          AZURE_TRANSLATOR_REGION: ${{ secrets.AZURE_TRANSLATOR_REGION }}
        run: |
          for input_file in ${{ steps.files.outputs.all }}; do 
            input_file_extension=${input_file: -7}
            if [[ "$input_file_extension" == "en.json" ]]; then
              echo "Processing ${input_file}..."
              echo "done_something=yes" >> $GITHUB_OUTPUT
              python3 ./scripts/sort_checklist.py --input-file $input_file
              python3 ./scripts/translate.py --input-file $input_file
            fi
          done

      # TO BE DELETED: file translation with external github action
      - name: Machine Translator
        if: ${{ false }}   # DISABLED
        id: translator
        uses: IEvangelist/resource-translator@v2.1.6
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        with:
          sourceLocale: en
          subscriptionKey: ${{ secrets.AZURE_TRANSLATOR_SUBSCRIPTION_KEY }}
          endpoint: ${{ secrets.AZURE_TRANSLATOR_ENDPOINT }}
          region: ${{ secrets.AZURE_TRANSLATOR_REGION }}
          toLocales: es,ja,ko,pt

      # TO BE DELETED: Get list of files generated by the translation
      - name: Get changed files
        if: ${{ false }}   # DISABLED
        id: changes
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=json::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .json$ | xargs)"        
      
      # TO BE DELETED: To correct some JSON changes introduce by the translation
      - name: Transform JSON files
        id: Transform
        # if: ${{ steps.translator.outputs.has-new-translations }} == 'true'
        if: ${{ false }}   # DISABLED
        run: |
          $inputFiles = "${{ steps.changes.outputs.json }}"
          ./.github/workflows/transform.ps1 $inputFiles
        shell: pwsh

      # Generate macro-free spreadsheets and Azure Monitor workbooks
      - name: setup python
        if: ${{ steps.translate.outputs.done_something }} == 'yes'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        if: ${{ steps.translate.outputs.done_something }} == 'yes'
        run: |
          python -m pip install --upgrade pip
          pip install requests openpyxl
      # Create Excel spreadsheets
      - name: execute excel python script # run file
        if: ${{ steps.translate.outputs.done_something }} == 'yes'
        run: |
          # python ./scripts/update_excel_openpyxl.py --checklist-file="${{ steps.files.outputs.all }}" --excel-file="./spreadsheet/review_checklist_empty.xlsx" --output-name-is-input-name --output-path="./spreadsheet/" --verbose
          # python ./scripts/update_excel_openpyxl.py --only-english --checklist-file="${{ steps.files.outputs.all }}" --excel-file="./spreadsheet/review_checklist_empty.xlsx" --output-name-is-input-name --output-path="./spreadsheet/" --verbose
          python3 ./scripts/update_excel_openpyxl.py --checklist-file="${{ steps.files.outputs.all }}" --find-all --excel-file="./spreadsheet/review_checklist_empty.xlsx" --output-name-is-input-name --output-path="./spreadsheet/macrofree/" --verbose
      # Create Azure Monitor workbooks
      - name: execute workbook python script # run file
        if: ${{ steps.translate.outputs.done_something }} == 'yes'
        run: |
          python3 ./scripts/workbook_create.py --checklist-file="${{ steps.files.outputs.all }}" --output-path="./workbooks/" --blocks-path="./workbooks/blocks/"

      # Create the PR if any change was made
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.10.1
        # if: ${{ steps.translator.outputs.has-new-translations }} == 'true'
        if: ${{ steps.translate.outputs.done_something }} == 'yes'
        with:
          # title: '${{ steps.translator.outputs.summary-title }}'
          # body: '${{ steps.translator.outputs.summary-details }}'
          title: 'Automatic translation of ${{ steps.files.outputs.all }}'
          body: 'Processed changed files ${{ steps.files.outputs.all }}'
